env:
  global:
    - IMG=ghdl/ghdl
    - DISTR=ubuntu20-mcode

services:
  - docker
  
before_install:
- docker pull $IMG:$DISTR
  
# Here are the list of run scripts of different DUTs/testcases
script:
    # Testing the installation of the ghdl
  - docker run -t $IMG:$DISTR ghdl --version
  
    # Mount the repo to docker, and run the hello world example
  - > 
    docker run -t -v `pwd`:/mnt/data $IMG:$DISTR
    /bin/bash -c  "chmod u+x /mnt/data/pin_out_onehot/sim.bash;
    /mnt/data/pin_out_onehot/sim.bash"
    